.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

issue와 pr에서 사용할 template을 작성해 보았습니다. 개선할 부분이 있다면 말씀해 주시면 감사하겠습니다.

chore: update issue templates

---

.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

커밋 메세지 규칙을 지켜야 커밋이 가능 하도록 하는 lint를 세팅했습니다.
해당안됨

chore: add commit message lint

---

.github/workflows/commit_lint.yml
commitlint.config.js

- remove the custom commit message type to use the recommended convection
- add commit lint git action workflow that runs on push and pull request
**Detailed descriptions of rules are in wiki**
(https://github.com/DevKor-github/OnTime-front/wiki/Git#commit-message-formats)
Closes #8

8 add commit lint to GitHub actions

---

.github/pull_request_template.md
.github/templates/bug_report.md
.github/templates/feature_request.md
.github/workflows/commit_lint.yml
commitlint.config.js

recover deleted github setting files

recover commit lint and issue templates

---

lib/config/database.dart
lib/data/daos/schedule_dao.dart
lib/main.dart

*Fixed error inside dao by removing dao object fields and using them from database object*
final UserDao userDao
userDao.createUser()
db.userDao.createUser()

Fixed dao usage

---

.gitignore
lib/config/database.dart
lib/config/database.g.dart
lib/data/daos/place_dao.dart
lib/data/daos/preparation_schedule_dao.dart
lib/data/daos/preparation_user_dao.dart
lib/data/daos/schedule_dao.dart
lib/data/daos/schedule_dao.g.dart
lib/data/daos/user_dao.dart
lib/data/tables/places_table.dart
lib/data/tables/preparation_schedule_table.dart
lib/data/tables/preparation_user_table.dart
lib/data/tables/schedules_table.dart
lib/data/tables/user_table.dart
lib/domain/entities/place_entity.dart
lib/domain/entities/preparation_schedule_entity.dart
lib/domain/entities/preparation_user_entity.dart
lib/domain/entities/schedule_entity.dart
lib/domain/entities/user_entity.dart
lib/main.dart
pubspec.lock
pubspec.yaml

chore: setup db new

---

lib/core/database/database.dart
lib/data/daos/preparation_schedule_dao.dart
lib/data/daos/preparation_user_dao.dart
lib/data/daos/user_dao.dart
lib/data/data_sources/schedule_local_data_source.dart
lib/data/data_sources/schedule_remote_data_source.dart
lib/data/repositories/schedule_repository_impl.dart
lib/data/tables/places_table.dart
lib/data/tables/preparation_schedule_table.dart
lib/data/tables/preparation_user_table.dart
lib/data/tables/schedules_table.dart
lib/data/tables/user_table.dart
lib/domain/entities/place_entity.dart
lib/domain/entities/preparation_step_entity.dart
lib/domain/entities/schedule_entity.dart
lib/domain/entities/user_entity.dart
lib/domain/repositories/preparation_repository.dart
lib/domain/repositories/schedule_repository.dart
pubspec.lock
pubspec.yaml
test/data/repositories/schedule_repository_impl_test.dart

35 change type of id to UUID

---

lib/data/data_sources/preparation_local_data_source.dart
lib/data/data_sources/preparation_remote_data_source.dart
lib/data/repositories/preparation_repository_impl.dart
lib/data/repositories/schedule_repository_impl.dart
lib/domain/repositories/preparation_repository.dart
lib/main.dart
pubspec.lock
test/data/repositories/preparation_repository_impl_test.dart
test/data/repositories/schedule_repository_impl_test.dart
test/helpers/mock.dart

- Create an implementation of the PreparationRepository
- Create an interface of PreparationRemoteDataSource
- Create an interface of PreparationLocalDataSource
- Mock both interfaces using mockito
- Create unit tests for every function in PreparationRepository

feat: Create implementation of PreparationRepository

---

lib/data/daos/preparation_schedule_dao.dart
lib/data/daos/preparation_user_dao.dart
lib/data/tables/preparation_schedule_table.dart
lib/data/tables/preparation_user_table.dart
lib/domain/entities/preparation_step_entity.dart
pubspec.lock
test/data/repositories/preparation_repository_impl_test.dart
widgetbook/pubspec.lock

- change preparation order to linked list

feat: change preparation order to linked list

---

commitlint.config.mjs

chore: add commitlint configuration for standardized commit messages

---

lib/presentation/home/screens/home_screen.dart
lib/presentation/onboarding/mutly_page_form.dart
lib/presentation/onboarding/onboarding_screen.dart
lib/presentation/schedule_create/compoenent/top_bar.dart
lib/presentation/schedule_create/screens/schedule_create_screen.dart
lib/presentation/schedule_create/screens/schedule_name_form.dart
lib/presentation/schedule_create/screens/schedule_place_moving_time_form.dart
lib/presentation/schedule_create/screens/schedule_spare_and_preparing_time_form.dart
lib/presentation/schedule_create/screens/schedule_time_form.dart
lib/presentation/shared/components/progress_bar.dart
lib/presentation/shared/router/go_router.dart

- create a schedule multipage form
- 
Closes #78

78 multipage form for schedule creation

---

lib/data/data_sources/token_local_data_source.dart
lib/data/models/sign_in_user_response_model.dart
lib/domain/entities/token_entity.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.lock
pubspec.yaml

- implement TokenLocalDataSource for secure token storage and retrieval
Closes #116

116 tokenlocaldatasource and securestorage

---

.gitignore
lib/data/data_sources/token_local_data_source.dart
lib/data/models/sign_in_user_response_model.dart
lib/data/repositories/authentication_repository_impl.dart
lib/domain/entities/token_entity.dart
lib/domain/entities/user_entity.dart
lib/main.dart
lib/presentation/app/bloc/app_bloc.dart
lib/presentation/app/bloc/app_event.dart
lib/presentation/app/bloc/app_state.dart
lib/presentation/app/screens/app.dart
lib/presentation/shared/router/go_router.dart
lib/presentation/shared/utils/stream_to_listenable.dart
lib/screens/test_screen.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
widgetbook/pubspec.lock

- create app bloc to handle authentication state
- make go router use bloc to redirect to login page
Closes #125

125 appbloc

---

.gitignore
lib/data/data_sources/token_local_data_source.dart
lib/data/models/sign_in_user_response_model.dart
lib/data/repositories/authentication_repository_impl.dart
lib/domain/entities/token_entity.dart
lib/domain/entities/user_entity.dart
lib/domain/repositories/user_repository.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.lock
pubspec.yaml

- create authentication repository
- use freezed on user entity to make empty user
Closes #115

115 authentication repository

---

lib/presentation/onboarding/cubit/onboarding/onboarding_state.dart
lib/presentation/onboarding/preparation_name_select/cubit/preparation_name/preparation_name_cubit.dart

급한 에러 해결
첫페이지에서 준비과정 스텝 선택 해제시 다음 순서변경 화면에서  모든 준비과정이 사라지는 에러 해결

138 준비과정 순서 설정 폼 리팩토링

---

.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/firebase_hosting_merge.yml
lib/presentation/onboarding/preparation_name_select/components/preparation_name_select_field.dart
lib/presentation/onboarding/preparation_order/components/preparation_reorderable_list.dart
lib/presentation/onboarding/preparation_order/components/reorderable_tile.dart
lib/presentation/onboarding/preparation_time/components/preparation_time_input_list.dart
lib/presentation/onboarding/preparation_time/components/preparation_time_tild.dart
lib/presentation/shared/components/check_button.dart
lib/presentation/shared/theme/theme.dart
widgetbook/lib/check_button.dart
widgetbook/lib/main.dart
widgetbook/lib/preparation_name_select_field.dart
widgetbook/lib/preparation_reorderable_list.dart
widgetbook/lib/preparation_time_input_field_list.dart
widgetbook/lib/preparation_time_tile.dart
widgetbook/lib/reorderable_tile.dart
widgetbook/lib/tile.dart
widgetbook/pubspec.lock
widgetbook/pubspec.yaml

- add tile components to widgetbook
- add list components to widgetbook
Closes #155

155 create tile list component

---

.github/ISSUE_TEMPLATE/ui_component_bug_report.yaml

feat: add UI component bug report template for widgetbook components

---

.gitignore
android/app/google-service.json
android/app/src/main/AndroidManifest.xml
package-lock.json
package.json
pubspec.lock
web/index.html

- 코드 내 구글, 카카오 키 삭제 
- gitignore 수정

chore: delete keys

---

lib/presentation/onboarding/components/onboarding_page_view_layout.dart
lib/presentation/onboarding/components/onboarding_title.dart
lib/presentation/onboarding/preparation_name_select/screens/preparation_name_form.dart
lib/presentation/onboarding/preparation_order/screens/preparation_order_form.dart
lib/presentation/onboarding/preparation_time/screens/preparation_time_form.dart
lib/presentation/onboarding/schedule_spare_time/screens/schedule_spare_time_form.dart
widgetbook/lib/onboarding_title.dart

- Onboarding title 디자인 적용
- 컴포넌트 분리
- 위젯북에 추가
Closes #161

161 create onboarding title component

---

lib/presentation/shared/theme/custom_text_theme.dart
lib/presentation/shared/theme/theme.dart

**Describe the feature you'd like**
- Create CustomTextTheme
- Add headlineExtraSmall
- Add titleExtraSmall
- Add bodyExtraLarge
- Add bodyExtraSmall
- Apply figma text theme to flutter text theme
**text theme 사용법**
Theme.of(context).textTheme.**custom.**[textStyle name]
**Figma Flutter Text Theme 대응 관계**
headline 1 -> headlineLarge
headline 2 -> headlineMedium
headline 3 -> headlineSmall
headline 4 -> headlineExtraSmall
title 1 -> titleLarge
title 2 -> titleMedium
title 3 -> titleSmall
title 4 -> titleExtraSmall
body 1 -> bodyExtraLarge
body 2 -> bodyLarge
body 3 -> bodyMedium
body 4 -> bodySmall
body 5 -> bodyExtraSmall
**Issue**
Closes #167

167 create customtexttheme and apply texttheme

---

lib/main.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
web/firebase-messaging-sw.js
web/index.html
widgetbook/macos/Flutter/GeneratedPluginRegistrant.swift
widgetbook/pubspec.lock
widgetbook/windows/flutter/generated_plugin_registrant.cc
widgetbook/windows/flutter/generated_plugins.cmake
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

- Configure firebase push notification
Closes #179 
- https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public

Setup firebase push notification

---

web/firebase-messaging-sw.js

- Fix Firebase push notification for web

Fix Firebase push notification for web

---

lib/presentation/alarm/bloc/alarm_screen/alarm_timer/alarm_timer_bloc.dart
lib/presentation/alarm/bloc/alarm_screen/alarm_timer/alarm_timer_state.dart
lib/presentation/alarm/components/alarm_screen/alarm_graph_animator.dart
lib/presentation/alarm/components/alarm_screen/preparation_step_tile.dart

알람 그래프 애니메이션 적용 

---

lib/presentation/alarm/bloc/alarm_screen_preparation_info/alarm_screen_preparation_info_bloc.dart
lib/presentation/alarm/bloc/alarm_screen_preparation_info/alarm_screen_preparation_info_state.dart
lib/presentation/alarm/bloc/alarm_timer/alarm_timer_bloc.dart
lib/presentation/alarm/bloc/alarm_timer/alarm_timer_event.dart
lib/presentation/alarm/bloc/alarm_timer/alarm_timer_state.dart
lib/presentation/alarm/components/alarm_screen_bottom_section.dart
lib/presentation/alarm/components/alarm_screen_top_section.dart
lib/presentation/alarm/screens/alarm_screen.dart
lib/presentation/alarm/screens/schedule_start_screen.dart
lib/presentation/early_late/screens/early_late_screen.dart
lib/presentation/shared/components/loading_screen.dart
lib/presentation/shared/router/go_router.dart
pubspec.lock

209 준비 종료 시 earlylatescreen으로 넘어가지 않는 문제 해결

---

lib/presentation/alarm/screens/alarm_screen.dart

- isLate, beforeOutTime을 timerState로 가져오는 것으로 수정,

fix: fix variables injected to early late screen

---

lib/presentation/alarm/screens/alarm_screen.dart
lib/presentation/early_late/components/check_list_box_widget.dart
lib/presentation/early_late/components/check_list_item_widget.dart
lib/presentation/early_late/components/early_late_message_image_widget.dart
lib/presentation/early_late/screens/early_late_screen.dart

- remove bloc logic from components in early late screen

refactor: remove bloc logic from components in early late screen

---

lib/core/services/device_info_service/device_info_service_mobile.dart
lib/core/services/device_info_service/device_info_service_unsupported.dart
lib/core/services/device_info_service/device_info_service_web.dart
lib/core/services/device_info_service/shared.dart
lib/core/services/js_interop_service.dart
lib/main.dart
web/functions.js

- 웹, 안드로이드, 아이폰 여부 가져오기
- 실행중인 os 타입 가져오기
- 홈화면에 추가된 상태에서 실행했는지 확인
Closes #219

디바이스 정보 제공 클래스

---

.github/ISSUE_TEMPLATE/design_modification.yaml

feat: add UI component design modification issue template

---

lib/main.dart
lib/presentation/app/screens/app.dart
lib/presentation/calendar/screens/calendar_screen.dart
lib/presentation/home/screens/home_screen_tmp.dart
lib/presentation/shared/components/calendar/centered_calendar_header.dart
lib/presentation/shared/theme/calendar_theme.dart
lib/presentation/shared/theme/theme.dart
pubspec.lock
pubspec.yaml

- Apply the design of calendar
- Create Calendar theme
#280

280 feature monthly calendar apply design

---

lib/presentation/home/bloc/schedule_timer_bloc.dart
lib/presentation/home/bloc/schedule_timer_event.dart
lib/presentation/home/bloc/schedule_timer_state.dart
lib/presentation/home/components/todays_schedule_tile.dart

- Added ScheduleTimerBloc to handle timer events and states.
- Created ScheduleTimerEvent and ScheduleTimerState classes for event and state management.
- Updated TodaysScheduleTile to utilize the new ScheduleTimerBloc for dynamic countdown display.

feat: implement ScheduleTimerBloc for managing schedule countdowns

---

lib/domain/use-cases/get_schedules_by_date_use_case.dart

- fix preparation start logic by sorting when getting todaysSchedule for nearestSchedule

fix: improve schedule filtering and sorting in GetSchedulesByDateUseCase
